---
# tasks file for remove

  - name: removing old kernels except the last two
    command: apt-get -y autoremove
    register: autoremove_output
    changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
